# Generated by Django 6.1 on 2026-08-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='status',
            field=models.CharField(choices=[('not_shipped', 'Not Shipped'), ('packaged', 'Packaged'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='not_shipped', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('modeling', 'Modeling Queue'), ('print', 'Print Queue'), ('paint', 'Paint Queue'), ('done', 'Done')], default='modeling', max_length=20),
        ),
    ]
