# Generated by Django 6.1 on 2026-08-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderboard', '0002_shipping_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
