# Generated by Django 6.1 on 2026-08-10 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderboard', '0003_order_order_received_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Order Created'), ('updated', 'Order Updated'), ('status_changed', 'Status Changed'), ('payment', 'Payment Added'), ('shipping', 'Shipping Updated'), ('photo', 'Photo Added'), ('note', 'Note')], max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='orderboard.order')),
            ],
        ),
    ]
